GET localhost:8080/persons

###

GET localhost:8080/persons/1

###

POST localhost:8080/persons
Content-Type: application/json

{
  "lastName": "Jane",
  "firstName": "Doe"
}

###

DELETE localhost:8080/persons/5