GET localhost:8080/persons

###

GET localhost:8080/persons/1
Authorization: Basic VXNlcjpkNWUzOTY0NS00ZjZjLTQyZTktOGQzYy1lYmI0NjhmOWRmNzE=

###

GET 127.0.0.1:8080/persons/1

###

GET 192.168.1.29:8080/persons/1

###

GET [fe80::5adf:66c0:1f35:ea72]:8080/persons/1

###

POST localhost:8080/auth/registration
Content-Type: application/json

{
  "lastName": "Jane",
  "firstName": "Doe",
  "userName": "jane_doe",
  "password": "pw12345789"
}

###

DELETE localhost:8080/persons/5