spring:
  # DataSource properties
  datasource:
    url: jdbc:mysql://localhost:3306/csbe
    username: root
    password: mypass
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate properties
  jpa:
    show-sql: true

  flyway:
    url: jdbc:mysql://localhost:3306/csbe
    user: root
    password: mypass
springdoc:
  default-produces-media-type: application/json
